version: '3.8'

services:
  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  # Backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - GARMIN_CLIENT_ID=${GARMIN_CLIENT_ID}
      - GARMIN_CLIENT_SECRET=${GARMIN_CLIENT_SECRET}
    env_file:
      - backend/app/.env
    volumes:
      - ./backend/app:/app/app

networks:
  default:
    name: trainlytics-network
