# Cloudflare Workers/Pages Configuration for Trainlytics
# https://developers.cloudflare.com/workers/wrangler/configuration/

name = "trainlytics-frontend"
compatibility_date = "2024-01-01"

# Pages configuration
pages_build_output_dir = "frontend/dist"

[build]
command = "cd frontend && npm install && npm run build"

[build.upload]
format = "service-worker"

# Environment variables for production
[env.production.vars]
VITE_APP_ENV = "production"

# Note: Sensitive variables should be set in Cloudflare Dashboard
# - VITE_API_URL
# - VITE_SUPABASE_URL
# - VITE_SUPABASE_ANON_KEY
