# Cloudflare Pages Configuration for Trainlytics
# https://developers.cloudflare.com/pages/

# Note: For Cloudflare Pages, build configuration is done in the dashboard, not here.
# The [build] section is NOT supported by Pages.

name = "trainlytics-frontend"
compatibility_date = "2024-01-01"

# Pages build output directory (for reference)
# Configure this in Cloudflare Pages Dashboard:
# Build command: cd frontend && npm install && npm run build
# Build output directory: frontend/dist

# Environment variables for production
# These should be set in Cloudflare Pages Dashboard:
# - VITE_APP_ENV = "production"
# - VITE_API_URL
# - VITE_SUPABASE_URL
# - VITE_SUPABASE_ANON_KEY
